site_name: Noktech Deploy
site_description: Advanced deployment client with multiple protocols support
site_author: Breno Nogueira
repo_url: https://github.com/noktech/deploy

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Guia:
    - Instalação: guide/installation.md
    - Uso: guide/usage.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Português
      link: /pt/
      lang: pt